import { z } from "zod";

export const loginSchema = z.object({
  username: z.string().min(1),
  password: z.string().min(1)
});

export const legacyScanSchema = z.object({
  path: z.string().min(1)
});

export const browseLocalFilesSchema = z.object({
  path: z.string().min(1).optional()
});

export const importBundleSchema = z.object({
  rootPath: z.string().min(1),
  bundleId: z.string().min(1).optional(),
  note: z.string().max(1024).optional()
});

export const pipelineStageSchema = z.enum(["convert", "extract", "tables", "graph", "viz"]);

export const modelConfigSchema = z.discriminatedUnion("provider", [
  z.object({
    provider: z.literal("deterministic"),
    model: z.literal("deterministic").default("deterministic")
  }),
  z.object({
    provider: z.literal("openai-compatible"),
    baseUrl: z.string().url().default("https://api.openai.com/v1"),
    model: z.string().min(1),
    apiKey: z.string().min(1).optional()
  }),
  z.object({
    provider: z.literal("anthropic"),
    baseUrl: z.string().url().default("https://api.anthropic.com/v1"),
    model: z.string().min(1),
    apiKey: z.string().min(1).optional()
  })
]);

export const buildRequestSchema = z.object({
  stages: z.array(pipelineStageSchema).min(1).default(["convert", "extract", "tables", "graph", "viz"]),
  model: z.string().min(1).default("deterministic"),
  modelConfig: modelConfigSchema.optional(),
  force: z.boolean().default(false),
  only: z.string().min(1).nullable().default(null),
  qualityProfileId: z.string().min(1).default("default"),
  generateAliases: z.boolean().default(false)
});

export const qualityProfileUpdateSchema = z.object({
  config: z.object({
    minPackageScore: z.number().min(0).max(1),
    rules: z.record(z.string(), z.record(z.string(), z.unknown()))
  })
});

export const modelConnectivitySchema = z.object({
  modelConfig: modelConfigSchema
});

export const createReleaseSchema = z.object({
  version: z.string().min(1),
  packageIds: z.array(z.string().min(1)).min(1)
});

export const rollbackReleaseSchema = z.object({
  releaseId: z.string().min(1)
});

/** 资产包/资料库/版本/发布的命名与备注更新校验：至少提供一个可编辑字段。 */
export const updatePackageSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(2000).optional()
}).refine((value) => value.name !== undefined || value.description !== undefined, {
  message: "至少提供 name 或 description。"
});

export const updateBundleSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(2000).optional()
}).refine((value) => value.name !== undefined || value.description !== undefined, {
  message: "至少提供 name 或 description。"
});

export const updateBundleVersionSchema = z.object({
  label: z.string().min(1).max(200).optional(),
  note: z.string().max(2000).optional()
}).refine((value) => value.label !== undefined || value.note !== undefined, {
  message: "至少提供 label 或 note。"
});

export const updateReleaseSchema = z.object({
  version: z.string().min(1).max(200).optional(),
  note: z.string().max(2000).optional()
}).refine((value) => value.version !== undefined || value.note !== undefined, {
  message: "至少提供 version 或 note。"
});

export const mcpQuerySchema = z.object({
  toolName: z.string().min(1),
  payload: z.record(z.string(), z.unknown()).default({})
});

export const pageTypeSpecSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  dir: z.string().min(1),
  template: z.string().min(1),
  requiredSections: z.array(z.string()).default([]),
  requiredFacts: z.array(z.string()).default([]),
  evidenceRequired: z.boolean().optional(),
  publishable: z.boolean().optional()
});

export const documentTypeSpecSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  description: z.string().default(""),
  defaultPageTypeId: z.string().min(1),
  wikiSpecTemplate: z.object({
    requiredSections: z.array(z.string()).default([]),
    requiredFacts: z.array(z.string()).default([]),
    evidenceRequired: z.boolean().default(true),
    guidance: z.string().default("")
  }),
  publishable: z.boolean().optional()
});

export const knowledgeRuleConfigSchema = z.object({
  documentTypes: z.record(z.string(), documentTypeSpecSchema).default({}),
  pageTypes: z.record(z.string(), pageTypeSpecSchema),
  entityTypes: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(1),
    publishable: z.boolean()
  })),
  relationTypes: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(1),
    direction: z.enum(["source_to_target", "bidirectional"]),
    publishable: z.boolean(),
    autoGenerated: z.boolean()
  })),
  tableRules: z.object({
    autoConfirmFieldIdSuffixes: z.array(z.string()).default([]),
    candidateFieldIdSuffixes: z.array(z.string()).default([])
  }),
  qualityRules: z.record(z.string(), z.record(z.string(), z.unknown())).default({})
});

export const createLegislationProfileSchema = z.object({
  name: z.string().min(1),
  config: knowledgeRuleConfigSchema,
  activate: z.boolean().default(false)
});

export const activateLegislationProfileSchema = z.object({
  profileId: z.string().min(1)
});

export const createAttributionAuditSchema = z.object({
  releaseId: z.string().min(1),
  title: z.string().min(1),
  segments: z.array(z.object({
    text: z.string().min(1),
    trace: z.object({
      releaseId: z.string().optional(),
      componentIds: z.array(z.string()).optional(),
      artifactIds: z.array(z.string()).optional(),
      sourceVersionIds: z.array(z.string()).optional(),
      evidenceIds: z.array(z.string()).optional()
    }).optional(),
    derivedFrom: z.array(z.string()).optional()
  })).min(1)
});

export const storageCategorySchema = z.enum(["blobs", "kb_build_runs", "web_imports", "releases", "logs"]);

export const reclaimRequestSchema = z.object({
  categories: z.array(storageCategorySchema).min(1)
});

export const packageListQuerySchema = z.object({
  q: z.string().min(1).optional(),
  status: z.enum(["draft", "reviewing", "approved", "published", "stale"]).optional(),
  kind: z.string().min(1).optional()
});

export const searchQuerySchema = z.object({
  q: z.string().min(1),
  limit: z.coerce.number().int().min(1).max(50).optional()
});

export const reviewTransitionSchema = z.object({
  taskIds: z.array(z.string().min(1)).min(1),
  status: z.enum(["open", "resolved", "dismissed"]),
  note: z.string().max(1024).optional()
});

export const tableAliasUpdateSchema = z.object({
  entries: z.array(z.object({
    canonical: z.string().min(1),
    aliases: z.array(z.string()).default([])
  })).min(1)
});

export const diagnosticLogQuerySchema = z.object({
  level: z.string().optional(),
  category: z.string().optional(),
  status: z.string().optional(),
  traceId: z.string().optional(),
  runId: z.string().optional(),
  releaseId: z.string().optional(),
  entityId: z.string().optional(),
  q: z.string().optional(),
  from: z.string().optional(),
  to: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(500).optional()
});
