export type UserRole = "admin" | "developer" | "maintainer" | "viewer";

export type AssetGroup =
  | "wiki"
  | "index"
  | "graph"
  | "table"
  | "evidence"
  | "quality"
  | "release";

export type PackageStatus = "draft" | "reviewing" | "approved" | "published" | "stale";
export type ReviewSeverity = "blocking" | "warning" | "info";
export type ReviewStatus = "open" | "resolved" | "dismissed";

export interface DatabaseHandle {
  adapter: import("./db-adapter").DatabaseAdapter;
  schema: string;
  close(): Promise<void>;
}

export interface UserRecord {
  id: string;
  username: string;
  passwordHash: string;
  role: UserRole;
  displayName: string;
}

export type SourceCategory = "gamedata" | "gamedocs";

export interface SourceBlob {
  contentHash: string;
  byteSize: number;
  storageUri: string;
  firstSeenAt: string;
}

export interface SourceBundle {
  bundleId: string;
  name: string;
  description: string;
  createdAt: string;
}

export interface SourceBundleVersion {
  versionId: string;
  bundleId: string;
  parentVersionId: string | null;
  label: string;
  note: string;
  createdBy: string;
  createdAt: string;
  fileCount: number;
  addedCount: number;
  modifiedCount: number;
  removedCount: number;
  unchangedCount: number;
  totalBytes: number;
}

export interface SourceFileEntry {
  versionId: string;
  logicalPath: string;
  category: SourceCategory;
  contentHash: string;
  byteSize: number;
}

export type SourceFileChange =
  | { kind: "added"; logicalPath: string; category: SourceCategory; contentHash: string }
  | { kind: "modified"; logicalPath: string; category: SourceCategory; contentHash: string; previousHash: string }
  | { kind: "removed"; logicalPath: string; category: SourceCategory; previousHash: string };

export interface ImportBundleResult {
  bundle: SourceBundle;
  version: SourceBundleVersion;
  changes: SourceFileChange[];
  newBlobCount: number;
}

export interface AssetPackage {
  packageId: string;
  name: string;
  kind: string;
  status: PackageStatus;
  description: string;
  createdByRunId: string;
  sourceVersionIds: string[];
  legacyPaths: string[];
  qualitySummary: Record<string, unknown>;
  createdAt: string;
}

export interface AssetComponent {
  componentId: string;
  packageId: string;
  artifactId: string;
  group: AssetGroup;
  kind: string;
  title: string;
  status: string;
  legacyPath: string;
  storageUri: string;
  sourceRefs: string[];
  quality: Record<string, unknown>;
}

export interface EvidenceRecord {
  evidenceId: string;
  packageId: string;
  componentId: string;
  sourceVersionId: string;
  quote: string;
  note: string;
  confidence: number;
  createdAt: string;
}

export interface EvidenceCoverage {
  totalComponents: number;
  coveredComponents: number;
  missingComponents: number;
  evidenceRecords: number;
  coverageRate: number;
}

export interface ReviewTask {
  taskId: string;
  packageId: string;
  componentId: string;
  severity: ReviewSeverity;
  status: ReviewStatus;
  title: string;
  description: string;
  suggestedAction: string;
  createdAt: string;
}

export interface ReleaseRecord {
  releaseId: string;
  version: string;
  status: "draft" | "published";
  packageIds: string[];
  publishedAt: string | null;
  publishedBy: string;
  createdBy: string;
  createdAt: string;
  manifestHash: string;
  manifest: Record<string, unknown>;
  qualityGate: Record<string, unknown>;
}

export interface AgentEvent {
  eventId: string;
  releaseId: string;
  query: string;
  hitComponentIds: string[];
  qualityFlags: string[];
  status: "hit" | "miss";
  feedbackType: "hit" | "miss" | "low_quality_hit" | "repeated_query" | "evidence_insufficient" | "relation_inference_failed";
  suggestedAction: string;
  taskId: string;
  createdAt: string;
}

export interface PageTypeSpec {
  id: string;
  label: string;
  dir: string;
  template: string;
  requiredSections: string[];
  requiredFacts: string[];
  evidenceRequired?: boolean;
  publishable?: boolean;
}

export interface WikiSpecTemplate {
  requiredSections: string[];
  requiredFacts: string[];
  evidenceRequired: boolean;
  guidance: string;
}

export interface DocumentTypeSpec {
  id: string;
  label: string;
  description: string;
  defaultPageTypeId: string;
  wikiSpecTemplate: WikiSpecTemplate;
  publishable?: boolean;
}

export interface EntityTypeSpec {
  id: string;
  label: string;
  publishable: boolean;
}

export interface RelationTypeSpec {
  id: string;
  label: string;
  direction: "source_to_target" | "bidirectional";
  publishable: boolean;
  autoGenerated: boolean;
}

export interface TableRuleSpec {
  autoConfirmFieldIdSuffixes: string[];
  candidateFieldIdSuffixes: string[];
}

export interface KnowledgeRuleConfig {
  documentTypes: Record<string, DocumentTypeSpec>;
  pageTypes: Record<string, PageTypeSpec>;
  entityTypes: EntityTypeSpec[];
  relationTypes: RelationTypeSpec[];
  tableRules: TableRuleSpec;
  qualityRules: Record<string, Record<string, unknown>>;
}

export interface KnowledgeRuleProfile {
  profileId: string;
  name: string;
  active: boolean;
  hash: string;
  config: KnowledgeRuleConfig;
  createdBy: string;
  updatedAt: string;
}

export type AttributionType = "引用" | "推导" | "创作" | "无法判断";

export interface AttributionSegment {
  segmentId: string;
  text: string;
  attributionType: AttributionType;
  trace: Partial<KnowledgeTrace>;
  derivedFrom: string[];
  risk: string;
}

export interface AttributionAudit {
  auditId: string;
  releaseId: string;
  title: string;
  segments: AttributionSegment[];
  createdBy: string;
  createdAt: string;
}

export interface McpAuditRecord {
  auditId: string;
  sessionId: string;
  agentRole: string;
  toolName: string;
  releaseId: string | null;
  queryPayload: Record<string, unknown>;
  hitComponentIds: string[];
  qualityFlags: string[];
  status: "hit" | "miss" | "error";
  latencyMs: number;
  createdAt: string;
}

export interface KnowledgeTrace {
  releaseId: string;
  componentIds: string[];
  artifactIds: string[];
  sourceVersionIds: string[];
  evidenceIds: string[];
}

export interface KnowledgeEnvelope<T = unknown> {
  release: {
    releaseId: string;
    version: string;
    publishedAt: string | null;
    manifestHash: string;
  };
  result: T;
  qualityFlags: string[];
  trace: KnowledgeTrace;
}

export type DiagnosticLogLevel = "debug" | "info" | "warn" | "error";
export type DiagnosticLogCategory = "http" | "source_import" | "kb_build" | "llm" | "release" | "mcp" | "db" | "system";
export type DiagnosticLogStatus = "started" | "completed" | "failed" | "event";

export interface DiagnosticLogRecord {
  logId: string;
  traceId: string;
  spanId: string;
  parentSpanId: string;
  level: DiagnosticLogLevel;
  category: DiagnosticLogCategory;
  message: string;
  status: DiagnosticLogStatus;
  durationMs: number | null;
  actor: string;
  route: string;
  method: string;
  entityType: string;
  entityId: string;
  runId: string;
  releaseId: string;
  requestPayload: Record<string, unknown>;
  context: Record<string, unknown>;
  errorName: string;
  errorMessage: string;
  errorStack: string;
  createdAt: string;
}

export interface DiagnosticSummary {
  errors24h: number;
  slowRequests24h: number;
  failedBuilds24h: number;
  mcpErrors24h: number;
  llmErrors24h: number;
}

export type PipelineStage = "convert" | "extract" | "tables" | "graph" | "viz";
export type BuildRunStatus = "running" | "completed" | "failed";
export type QualitySeverity = "blocking" | "warning" | "info";

export interface KnowledgeBuildRun {
  runId: string;
  sourceVersionId: string;
  packageId: string | null;
  adapter: "native";
  stages: PipelineStage[];
  model: string;
  wikiSpecsHash: string;
  qualityProfileId: string;
  status: BuildRunStatus;
  currentStage: string;
  completedStages: string[];
  startedAt: string;
  finishedAt: string | null;
  error: string;
  outputUri: string;
  config: Record<string, unknown>;
}

export interface QualityGateProfile {
  profileId: string;
  name: string;
  active: boolean;
  config: QualityGateConfig;
  createdBy: string;
  updatedAt: string;
}

export interface QualityGateConfig {
  minPackageScore: number;
  rules: Record<string, Record<string, unknown>>;
}

export interface QualityFinding {
  ruleId: string;
  severity: QualitySeverity;
  componentId?: string;
  title: string;
  description: string;
  suggestedAction: string;
  scoreImpact: number;
}

// --- Storage maintenance (disk GC) ---

export type StorageCategory = "blobs" | "kb_build_runs" | "web_imports" | "releases" | "logs";

export type StorageEntryStatus = "live" | "reclaimable";

export interface StorageEntry {
  category: StorageCategory;
  key: string;            // dir / file name, e.g. runId, releaseId, blob filename, log filename
  bytes: number;
  fileCount: number;
  oldestMs: number | null;
  newestMs: number | null;
  status: StorageEntryStatus;
  reason: string;         // human-readable liveness reason
}

export interface StorageCategorySummary {
  category: StorageCategory;
  totalBytes: number;
  fileCount: number;
  entryCount: number;
  liveBytes: number;
  reclaimableBytes: number;
  reclaimableEntries: number;
  oldestMs: number | null;
  newestMs: number | null;
}

export interface StorageOverview {
  categories: StorageCategorySummary[];
  totalBytes: number;
  reclaimableBytes: number;
  scannedAt: string;
}

export interface StorageScanReport extends StorageOverview {
  entries: StorageEntry[];
}

export interface ReclaimRequest {
  categories: StorageCategory[];
}

export interface ReclaimResult {
  deletedEntries: number;
  reclaimedBytes: number;
  perCategory: Partial<Record<StorageCategory, { count: number; bytes: number }>>;
}

// --- Cross-entity search ---

export type SearchHitKind = "package" | "component" | "source_version" | "release";

export interface SearchHit {
  kind: SearchHitKind;
  id: string;             // packageId / componentId / versionId / releaseId
  title: string;
  subtitle: string;
  packageId?: string;     // for component -> Assets navigation + its owning package
}

export interface SearchResult {
  query: string;
  hits: SearchHit[];
}
