import { describe, expect, it } from "vitest";

import { createDatabase } from "../src/server/db";
import { createLegislationService } from "../src/server/services/legislationService";
import { TEST_DATABASE_URL } from "./helpers/testEnv";
import { createTestDb } from "./helpers/testDb";

describe("LegislationService", () => {
  it("seeds a deterministic default profile and versions activated updates", async () => {
    const { db, cleanup } = await createTestDb();
    try {
      const service = createLegislationService(db);

      const first = await service.getActiveProfile();
      const second = await service.getActiveProfile();
      expect(first.profileId).toBe("default");
      expect(first.active).toBe(true);
      expect(first.hash).toBe(second.hash);
      expect(first.config.documentTypes.system_rule.wikiSpecTemplate.requiredSections).toContain("核心规则");
      expect(first.config.pageTypes.system.requiredSections).toContain("核心规则");
      expect(first.config.entityTypes.some((item) => item.id === "system")).toBe(true);
      expect(first.config.relationTypes.some((item) => item.id === "configured_in")).toBe(true);

      const created = await service.createProfile({
        name: "Combat rules",
        config: {
          ...first.config,
          entityTypes: [...first.config.entityTypes, { id: "buff", label: "Buff", publishable: true }],
        },
        createdBy: "admin",
        activate: false,
      });
      expect(created.active).toBe(false);
      expect((await service.getActiveProfile()).profileId).toBe("default");

      const activated = await service.activateProfile(created.profileId, "lead");
      expect(activated.active).toBe(true);
      expect(activated.hash).not.toBe(first.hash);
      expect((await service.getActiveProfile()).profileId).toBe(created.profileId);
    } finally {
      await cleanup();
    }
  }, 15000);

  it("upgrades the system default profile when an existing database has the old rule shape", async () => {
    const { db, schema, cleanup } = await createTestDb();
    const oldDefaultConfig = {
      pageTypes: {
        system: {
          id: "system",
          label: "系统规则",
          dir: "systems",
          template: "system_rule.md",
          requiredSections: ["Overview"],
          requiredFacts: ["config_table"],
          evidenceRequired: true,
          publishable: true
        }
      },
      entityTypes: [{ id: "system", label: "系统", publishable: true }],
      relationTypes: [{ id: "configured_in", label: "配置于", direction: "source_to_target", publishable: true, autoGenerated: false }],
      tableRules: { autoConfirmFieldIdSuffixes: ["Id"], candidateFieldIdSuffixes: [] },
      qualityRules: {}
    };

    try {
      await db.adapter.query("UPDATE knowledge_rule_profiles SET config_json = $2, hash = '' WHERE profile_id = $1", ["default", oldDefaultConfig]);

      const migrated = await createDatabase({ databaseUrl: TEST_DATABASE_URL, schema, seedUsers: false });
      try {
        const profile = await createLegislationService(migrated).getActiveProfile();
        expect(profile.config.documentTypes.system_rule.wikiSpecTemplate.requiredSections).toContain("核心规则");
        expect(profile.config.pageTypes.activity.requiredFacts).toContain("reward");
      } finally {
        await migrated.close();
      }
    } finally {
      await cleanup();
    }
  }, 15000);
});
