import { describe, expect, it } from "vitest";

import {
  addEntityType,
  addPageType,
  addRelationType,
  createRuleDraft,
  parseTagText,
  renamePageType,
  setPageTypeTags,
  updateTableRuleTags
} from "../src/client/src/pages/legislationEditor";
import type { KnowledgeRuleConfig } from "../src/client/src/api/types";

const baseConfig: KnowledgeRuleConfig = {
  pageTypes: {
    system: {
      id: "system",
      label: "系统规则",
      dir: "systems",
      template: "system.md",
      requiredSections: ["Overview"],
      requiredFacts: ["config_table"],
      evidenceRequired: true,
      publishable: true
    }
  },
  entityTypes: [{ id: "system", label: "系统", publishable: true }],
  relationTypes: [{ id: "depends_on", label: "依赖", direction: "source_to_target", publishable: true, autoGenerated: false }],
  tableRules: {
    autoConfirmFieldIdSuffixes: ["Id"],
    candidateFieldIdSuffixes: []
  },
  qualityRules: {}
};

describe("legislation editor model", () => {
  it("parses planner-entered tag text with mixed separators", () => {
    expect(parseTagText("Overview、Data Dependencies, Evidence\nQuality  ")).toEqual([
      "Overview",
      "Data Dependencies",
      "Evidence",
      "Quality"
    ]);
  });

  it("creates isolated drafts and edits page type tags without mutating source config", () => {
    const draft = createRuleDraft(baseConfig);
    const next = setPageTypeTags(draft, "system", "requiredSections", "Overview、Evidence");

    expect(next.pageTypes.system.requiredSections).toEqual(["Overview", "Evidence"]);
    expect(baseConfig.pageTypes.system.requiredSections).toEqual(["Overview"]);
  });

  it("keeps page type map keys aligned when the page type id is renamed", () => {
    const draft = createRuleDraft(baseConfig);
    const next = renamePageType(draft, "system", "system_rule");

    expect(next.pageTypes.system).toBeUndefined();
    expect(next.pageTypes.system_rule.id).toBe("system_rule");
    expect(next.pageTypes.system_rule.label).toBe("系统规则");
  });

  it("adds sensible defaults for new visual rule rows", () => {
    const withPage = addPageType(baseConfig);
    const withEntity = addEntityType(baseConfig);
    const withRelation = addRelationType(baseConfig);

    expect(withPage.pageTypes.page_type_2).toMatchObject({ label: "新页面类型", evidenceRequired: true, publishable: true });
    expect(withEntity.entityTypes.at(-1)).toEqual({ id: "entity_type_2", label: "新实体类型", publishable: true });
    expect(withRelation.relationTypes.at(-1)).toEqual({
      id: "relation_type_2",
      label: "新关系类型",
      direction: "source_to_target",
      publishable: true,
      autoGenerated: false
    });
  });

  it("updates table rule tag groups from non-json text", () => {
    const next = updateTableRuleTags(baseConfig, "candidateFieldIdSuffixes", "Ref、Link, Related");

    expect(next.tableRules.candidateFieldIdSuffixes).toEqual(["Ref", "Link", "Related"]);
  });
});
