import { describe, expect, it } from "vitest";

import {
  addEntityType,
  addDocumentType,
  addPageType,
  addRelationType,
  createRuleDraft,
  parseTagText,
  renamePageType,
  setDocumentTypeTags,
  setPageTypeTags,
  updateDocumentType,
  updateTableRuleTags
} from "../src/client/src/pages/legislationEditor";
import type { KnowledgeRuleConfig } from "../src/client/src/api/types";

const baseConfig: KnowledgeRuleConfig = {
  documentTypes: {
    system_rule: {
      id: "system_rule",
      label: "系统规则文档",
      description: "系统规则资料",
      defaultPageTypeId: "system",
      wikiSpecTemplate: {
        requiredSections: ["Overview"],
        requiredFacts: ["config_table"],
        evidenceRequired: true,
        guidance: "说明系统规则"
      },
      publishable: true
    }
  },
  pageTypes: {
    system: {
      id: "system",
      label: "系统规则",
      dir: "systems",
      template: "system.md",
      requiredSections: ["Overview"],
      requiredFacts: ["config_table"],
      evidenceRequired: true,
      publishable: true
    }
  },
  entityTypes: [{ id: "system", label: "系统", publishable: true }],
  relationTypes: [{ id: "depends_on", label: "依赖", direction: "source_to_target", publishable: true, autoGenerated: false }],
  tableRules: {
    autoConfirmFieldIdSuffixes: ["Id"],
    candidateFieldIdSuffixes: []
  },
  qualityRules: {}
};

describe("legislation editor model", () => {
  it("parses planner-entered tag text with mixed separators", () => {
    expect(parseTagText("Overview、Data Dependencies, Evidence\nQuality  ")).toEqual([
      "Overview",
      "Data Dependencies",
      "Evidence",
      "Quality"
    ]);
  });

  it("creates isolated drafts and edits page type tags without mutating source config", () => {
    const draft = createRuleDraft(baseConfig);
    const next = setPageTypeTags(draft, "system", "requiredSections", "Overview、Evidence");

    expect(next.pageTypes.system.requiredSections).toEqual(["Overview", "Evidence"]);
    expect(baseConfig.pageTypes.system.requiredSections).toEqual(["Overview"]);
  });

  it("keeps page type map keys aligned when the page type id is renamed", () => {
    const draft = createRuleDraft(baseConfig);
    const next = renamePageType(draft, "system", "system_rule");

    expect(next.pageTypes.system).toBeUndefined();
    expect(next.pageTypes.system_rule.id).toBe("system_rule");
    expect(next.pageTypes.system_rule.label).toBe("系统规则");
  });

  it("adds sensible defaults for new visual rule rows", () => {
    const withDocument = addDocumentType(baseConfig);
    const withPage = addPageType(baseConfig);
    const withEntity = addEntityType(baseConfig);
    const withRelation = addRelationType(baseConfig);

    expect(withDocument.documentTypes.document_type_2).toMatchObject({ label: "新文档类型", defaultPageTypeId: "document_type_2" });
    expect(withDocument.pageTypes.document_type_2.requiredSections).toEqual(["概览", "关键规则", "证据"]);
    expect(withPage.pageTypes.page_type_2).toMatchObject({ label: "新页面类型", evidenceRequired: true, publishable: true });
    expect(withEntity.entityTypes.at(-1)).toEqual({ id: "entity_type_2", label: "新实体类型", publishable: true });
    expect(withRelation.relationTypes.at(-1)).toEqual({
      id: "relation_type_2",
      label: "新关系类型",
      direction: "source_to_target",
      publishable: true,
      autoGenerated: false
    });
  });

  it("syncs document wiki templates to the matching page type rule", () => {
    const withSections = setDocumentTypeTags(baseConfig, "system_rule", "requiredSections", "概览、核心规则、证据");
    const withFacts = setDocumentTypeTags(withSections, "system_rule", "requiredFacts", "source、config_table");
    const next = updateDocumentType(withFacts, "system_rule", {
      wikiSpecTemplate: {
        ...withFacts.documentTypes.system_rule.wikiSpecTemplate,
        evidenceRequired: false
      }
    });

    expect(next.documentTypes.system_rule.wikiSpecTemplate.requiredSections).toEqual(["概览", "核心规则", "证据"]);
    expect(next.pageTypes.system.requiredSections).toEqual(["概览", "核心规则", "证据"]);
    expect(next.pageTypes.system.requiredFacts).toEqual(["source", "config_table"]);
    expect(next.pageTypes.system.evidenceRequired).toBe(false);
  });

  it("updates table rule tag groups from non-json text", () => {
    const next = updateTableRuleTags(baseConfig, "candidateFieldIdSuffixes", "Ref、Link, Related");

    expect(next.tableRules.candidateFieldIdSuffixes).toEqual(["Ref", "Link", "Related"]);
  });
});
