import type { EntityTypeSpec, KnowledgeRuleConfig, PageTypeSpec, RelationTypeSpec } from "../api/types";

type PageTagField = "requiredSections" | "requiredFacts";
type TableRuleField = "autoConfirmFieldIdSuffixes" | "candidateFieldIdSuffixes";

export function createRuleDraft(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  return {
    pageTypes: Object.fromEntries(Object.entries(config.pageTypes ?? {}).map(([key, value]) => [key, {
      ...value,
      requiredSections: [...(value.requiredSections ?? [])],
      requiredFacts: [...(value.requiredFacts ?? [])]
    }])),
    entityTypes: [...(config.entityTypes ?? [])].map((item) => ({ ...item })),
    relationTypes: [...(config.relationTypes ?? [])].map((item) => ({ ...item })),
    tableRules: {
      autoConfirmFieldIdSuffixes: [...(config.tableRules?.autoConfirmFieldIdSuffixes ?? [])],
      candidateFieldIdSuffixes: [...(config.tableRules?.candidateFieldIdSuffixes ?? [])]
    },
    qualityRules: Object.fromEntries(Object.entries(config.qualityRules ?? {}).map(([key, value]) => [key, { ...value }]))
  };
}

export function parseTagText(value: string): string[] {
  const seen = new Set<string>();
  return value
    .split(/[、,\n;]/)
    .map((item) => item.trim())
    .filter((item) => item.length > 0)
    .filter((item) => {
      if (seen.has(item)) return false;
      seen.add(item);
      return true;
    });
}

export function setPageTypeTags(config: KnowledgeRuleConfig, pageTypeId: string, field: PageTagField, value: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.pageTypes[pageTypeId];
  if (!spec) return draft;
  draft.pageTypes[pageTypeId] = { ...spec, [field]: parseTagText(value) };
  return draft;
}

export function renamePageType(config: KnowledgeRuleConfig, previousId: string, nextId: string): KnowledgeRuleConfig {
  const normalizedId = normalizeId(nextId);
  if (!normalizedId) return createRuleDraft(config);
  const draft = createRuleDraft(config);
  const existing = draft.pageTypes[previousId];
  if (!existing) return draft;
  delete draft.pageTypes[previousId];
  draft.pageTypes[normalizedId] = normalizePageType({ ...existing, id: normalizedId });
  return draft;
}

export function addPageType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("page_type", Object.keys(draft.pageTypes));
  draft.pageTypes[id] = normalizePageType({
    id,
    label: "新页面类型",
    dir: `${id}s`,
    template: `${id}.md`,
    requiredSections: ["Overview"],
    requiredFacts: [],
    evidenceRequired: true,
    publishable: true
  });
  return draft;
}

export function addEntityType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("entity_type", draft.entityTypes.map((item) => item.id));
  draft.entityTypes = [...draft.entityTypes, { id, label: "新实体类型", publishable: true }];
  return draft;
}

export function addRelationType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("relation_type", draft.relationTypes.map((item) => item.id));
  draft.relationTypes = [...draft.relationTypes, {
    id,
    label: "新关系类型",
    direction: "source_to_target",
    publishable: true,
    autoGenerated: false
  }];
  return draft;
}

export function updateTableRuleTags(config: KnowledgeRuleConfig, field: TableRuleField, value: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.tableRules = { ...draft.tableRules, [field]: parseTagText(value) };
  return draft;
}

export function updatePageType(config: KnowledgeRuleConfig, pageTypeId: string, patch: Partial<PageTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.pageTypes[pageTypeId];
  if (!spec) return draft;
  if (patch.id && patch.id !== pageTypeId) return renamePageType(draft, pageTypeId, patch.id);
  draft.pageTypes[pageTypeId] = normalizePageType({ ...spec, ...patch, id: pageTypeId });
  return draft;
}

export function removePageType(config: KnowledgeRuleConfig, pageTypeId: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  delete draft.pageTypes[pageTypeId];
  return draft;
}

export function updateEntityType(config: KnowledgeRuleConfig, index: number, patch: Partial<EntityTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.entityTypes = draft.entityTypes.map((item, itemIndex) => itemIndex === index ? normalizeEntityType({ ...item, ...patch }) : item);
  return draft;
}

export function removeEntityType(config: KnowledgeRuleConfig, index: number): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.entityTypes = draft.entityTypes.filter((_, itemIndex) => itemIndex !== index);
  return draft;
}

export function updateRelationType(config: KnowledgeRuleConfig, index: number, patch: Partial<RelationTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.relationTypes = draft.relationTypes.map((item, itemIndex) => itemIndex === index ? normalizeRelationType({ ...item, ...patch }) : item);
  return draft;
}

export function removeRelationType(config: KnowledgeRuleConfig, index: number): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.relationTypes = draft.relationTypes.filter((_, itemIndex) => itemIndex !== index);
  return draft;
}

export function updateQualityRule(config: KnowledgeRuleConfig, ruleId: string, patch: Record<string, unknown>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.qualityRules[ruleId] = { ...(draft.qualityRules[ruleId] ?? {}), ...patch };
  return draft;
}

export function removeQualityRule(config: KnowledgeRuleConfig, ruleId: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  delete draft.qualityRules[ruleId];
  return draft;
}

export function addQualityRule(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("quality_rule", Object.keys(draft.qualityRules));
  draft.qualityRules[id] = { severity: "warning", enabled: true, description: "新质量红线" };
  return draft;
}

function normalizePageType(spec: PageTypeSpec): PageTypeSpec {
  return {
    id: normalizeId(spec.id),
    label: spec.label.trim() || spec.id,
    dir: spec.dir.trim() || `${spec.id}s`,
    template: spec.template.trim() || `${spec.id}.md`,
    requiredSections: [...(spec.requiredSections ?? [])],
    requiredFacts: [...(spec.requiredFacts ?? [])],
    evidenceRequired: spec.evidenceRequired !== false,
    publishable: spec.publishable !== false
  };
}

function normalizeEntityType(spec: EntityTypeSpec): EntityTypeSpec {
  const id = normalizeId(spec.id);
  return { id, label: spec.label.trim() || id, publishable: spec.publishable !== false };
}

function normalizeRelationType(spec: RelationTypeSpec): RelationTypeSpec {
  const id = normalizeId(spec.id);
  return {
    id,
    label: spec.label.trim() || id,
    direction: spec.direction === "bidirectional" ? "bidirectional" : "source_to_target",
    publishable: spec.publishable !== false,
    autoGenerated: Boolean(spec.autoGenerated)
  };
}

function normalizeId(value: string): string {
  return value.trim().replace(/\s+/g, "_");
}

function nextId(prefix: string, existing: string[]): string {
  const taken = new Set(existing);
  let index = existing.length + 1;
  let candidate = `${prefix}_${index}`;
  while (taken.has(candidate)) {
    index += 1;
    candidate = `${prefix}_${index}`;
  }
  return candidate;
}
