import type { DocumentTypeSpec, EntityTypeSpec, KnowledgeGovernanceRules, KnowledgeRuleConfig, PageTypeSpec, RelationTypeSpec } from "../api/types";

type PageTagField = "requiredSections" | "requiredFacts";
type DocumentTagField = "requiredSections" | "requiredFacts";
type TableRuleField = "autoConfirmFieldIdSuffixes" | "candidateFieldIdSuffixes";
type GovernanceSection = keyof KnowledgeGovernanceRules;

export function createRuleDraft(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  return {
    documentTypes: Object.fromEntries(Object.entries(config.documentTypes ?? {}).map(([key, value]) => [key, {
      ...value,
      wikiSpecTemplate: {
        requiredSections: [...(value.wikiSpecTemplate?.requiredSections ?? [])],
        requiredFacts: [...(value.wikiSpecTemplate?.requiredFacts ?? [])],
        evidenceRequired: value.wikiSpecTemplate?.evidenceRequired !== false,
        guidance: value.wikiSpecTemplate?.guidance ?? ""
      }
    }])),
    pageTypes: Object.fromEntries(Object.entries(config.pageTypes ?? {}).map(([key, value]) => [key, {
      ...value,
      requiredSections: [...(value.requiredSections ?? [])],
      requiredFacts: [...(value.requiredFacts ?? [])]
    }])),
    entityTypes: [...(config.entityTypes ?? [])].map((item) => ({ ...item })),
    relationTypes: [...(config.relationTypes ?? [])].map((item) => ({ ...item })),
    tableRules: {
      autoConfirmFieldIdSuffixes: [...(config.tableRules?.autoConfirmFieldIdSuffixes ?? [])],
      candidateFieldIdSuffixes: [...(config.tableRules?.candidateFieldIdSuffixes ?? [])]
    },
    qualityRules: Object.fromEntries(Object.entries(config.qualityRules ?? {}).map(([key, value]) => [key, { ...value }])),
    governanceRules: cloneGovernanceRules(config.governanceRules)
  };
}

export function parseTagText(value: string): string[] {
  const seen = new Set<string>();
  return value
    .split(/[、,\n;]/)
    .map((item) => item.trim())
    .filter((item) => item.length > 0)
    .filter((item) => {
      if (seen.has(item)) return false;
      seen.add(item);
      return true;
    });
}

export function setPageTypeTags(config: KnowledgeRuleConfig, pageTypeId: string, field: PageTagField, value: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.pageTypes[pageTypeId];
  if (!spec) return draft;
  draft.pageTypes[pageTypeId] = { ...spec, [field]: parseTagText(value) };
  return draft;
}

export function renamePageType(config: KnowledgeRuleConfig, previousId: string, nextId: string): KnowledgeRuleConfig {
  const normalizedId = normalizeId(nextId);
  if (!normalizedId) return createRuleDraft(config);
  const draft = createRuleDraft(config);
  const existing = draft.pageTypes[previousId];
  if (!existing) return draft;
  delete draft.pageTypes[previousId];
  draft.pageTypes[normalizedId] = normalizePageType({ ...existing, id: normalizedId });
  return draft;
}

export function addDocumentType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("document_type", Object.keys(draft.documentTypes));
  const doc = normalizeDocumentType({
    id,
    label: "新文档类型",
    description: "说明这类资料进入知识库后应该回答什么问题。",
    defaultPageTypeId: id,
    wikiSpecTemplate: {
      requiredSections: ["概览", "关键规则", "证据"],
      requiredFacts: ["source"],
      evidenceRequired: true,
      guidance: "适用于需要主策划确认口径的新资料类型。"
    },
    publishable: true
  });
  draft.documentTypes[id] = doc;
  syncPageTypeFromDocument(draft, doc);
  return draft;
}

export function addPageType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("page_type", Object.keys(draft.pageTypes));
  draft.pageTypes[id] = normalizePageType({
    id,
    label: "新页面类型",
    dir: `${id}s`,
    template: `${id}.md`,
    requiredSections: ["Overview"],
    requiredFacts: [],
    evidenceRequired: true,
    publishable: true
  });
  return draft;
}

export function addEntityType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("entity_type", draft.entityTypes.map((item) => item.id));
  draft.entityTypes = [...draft.entityTypes, { id, label: "新实体类型", publishable: true }];
  return draft;
}

export function addRelationType(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("relation_type", draft.relationTypes.map((item) => item.id));
  draft.relationTypes = [...draft.relationTypes, {
    id,
    label: "新关系类型",
    direction: "source_to_target",
    publishable: true,
    autoGenerated: false
  }];
  return draft;
}

export function updateTableRuleTags(config: KnowledgeRuleConfig, field: TableRuleField, value: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.tableRules = { ...draft.tableRules, [field]: parseTagText(value) };
  return draft;
}

export function updateDocumentType(config: KnowledgeRuleConfig, documentTypeId: string, patch: Partial<DocumentTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.documentTypes[documentTypeId];
  if (!spec) return draft;
  if (patch.id && patch.id !== documentTypeId) return renameDocumentType(draft, documentTypeId, patch.id);
  const next = normalizeDocumentType({ ...spec, ...patch, id: documentTypeId });
  draft.documentTypes[documentTypeId] = next;
  syncPageTypeFromDocument(draft, next);
  return draft;
}

export function setDocumentTypeTags(config: KnowledgeRuleConfig, documentTypeId: string, field: DocumentTagField, value: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.documentTypes[documentTypeId];
  if (!spec) return draft;
  const next = normalizeDocumentType({
    ...spec,
    wikiSpecTemplate: {
      ...spec.wikiSpecTemplate,
      [field]: parseTagText(value)
    }
  });
  draft.documentTypes[documentTypeId] = next;
  syncPageTypeFromDocument(draft, next);
  return draft;
}

export function removeDocumentType(config: KnowledgeRuleConfig, documentTypeId: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  delete draft.documentTypes[documentTypeId];
  return draft;
}

export function updatePageType(config: KnowledgeRuleConfig, pageTypeId: string, patch: Partial<PageTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const spec = draft.pageTypes[pageTypeId];
  if (!spec) return draft;
  if (patch.id && patch.id !== pageTypeId) return renamePageType(draft, pageTypeId, patch.id);
  draft.pageTypes[pageTypeId] = normalizePageType({ ...spec, ...patch, id: pageTypeId });
  return draft;
}

export function removePageType(config: KnowledgeRuleConfig, pageTypeId: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  delete draft.pageTypes[pageTypeId];
  return draft;
}

export function updateEntityType(config: KnowledgeRuleConfig, index: number, patch: Partial<EntityTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.entityTypes = draft.entityTypes.map((item, itemIndex) => itemIndex === index ? normalizeEntityType({ ...item, ...patch }) : item);
  return draft;
}

export function removeEntityType(config: KnowledgeRuleConfig, index: number): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.entityTypes = draft.entityTypes.filter((_, itemIndex) => itemIndex !== index);
  return draft;
}

export function updateRelationType(config: KnowledgeRuleConfig, index: number, patch: Partial<RelationTypeSpec>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.relationTypes = draft.relationTypes.map((item, itemIndex) => itemIndex === index ? normalizeRelationType({ ...item, ...patch }) : item);
  return draft;
}

export function removeRelationType(config: KnowledgeRuleConfig, index: number): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.relationTypes = draft.relationTypes.filter((_, itemIndex) => itemIndex !== index);
  return draft;
}

export function updateQualityRule(config: KnowledgeRuleConfig, ruleId: string, patch: Record<string, unknown>): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.qualityRules[ruleId] = { ...(draft.qualityRules[ruleId] ?? {}), ...patch };
  return draft;
}

export function updateGovernanceRule<S extends GovernanceSection>(
  config: KnowledgeRuleConfig,
  section: S,
  patch: Partial<KnowledgeGovernanceRules[S]>
): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.governanceRules = {
    ...draft.governanceRules,
    [section]: {
      ...draft.governanceRules[section],
      ...patch
    }
  };
  return draft;
}

export function updateGovernanceTags(
  config: KnowledgeRuleConfig,
  section: "evidence",
  field: "requiredComponentKinds" | "citationRequiredOkfTypes",
  value: string,
): KnowledgeRuleConfig;
export function updateGovernanceTags(
  config: KnowledgeRuleConfig,
  section: "lint",
  field: "enabledDomains" | "blockingDomains",
  value: string,
): KnowledgeRuleConfig;
export function updateGovernanceTags(
  config: KnowledgeRuleConfig,
  section: "evidence" | "lint",
  field: string,
  value: string,
): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  draft.governanceRules = {
    ...draft.governanceRules,
    [section]: {
      ...draft.governanceRules[section],
      [field]: parseTagText(value)
    }
  };
  return draft;
}

export function removeQualityRule(config: KnowledgeRuleConfig, ruleId: string): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  delete draft.qualityRules[ruleId];
  return draft;
}

export function addQualityRule(config: KnowledgeRuleConfig): KnowledgeRuleConfig {
  const draft = createRuleDraft(config);
  const id = nextId("quality_rule", Object.keys(draft.qualityRules));
  draft.qualityRules[id] = { severity: "warning", enabled: true, description: "新质量红线" };
  return draft;
}

function renameDocumentType(config: KnowledgeRuleConfig, previousId: string, nextId: string): KnowledgeRuleConfig {
  const normalizedId = normalizeId(nextId);
  if (!normalizedId) return createRuleDraft(config);
  const draft = createRuleDraft(config);
  const existing = draft.documentTypes[previousId];
  if (!existing) return draft;
  delete draft.documentTypes[previousId];
  const next = normalizeDocumentType({ ...existing, id: normalizedId });
  draft.documentTypes[normalizedId] = next;
  syncPageTypeFromDocument(draft, next);
  return draft;
}

function normalizeDocumentType(spec: DocumentTypeSpec): DocumentTypeSpec {
  const id = normalizeId(spec.id);
  const defaultPageTypeId = normalizeId(spec.defaultPageTypeId || id);
  return {
    id,
    label: spec.label.trim() || id,
    description: spec.description.trim(),
    defaultPageTypeId,
    wikiSpecTemplate: {
      requiredSections: [...(spec.wikiSpecTemplate?.requiredSections ?? [])],
      requiredFacts: [...(spec.wikiSpecTemplate?.requiredFacts ?? [])],
      evidenceRequired: spec.wikiSpecTemplate?.evidenceRequired !== false,
      guidance: spec.wikiSpecTemplate?.guidance?.trim() ?? ""
    },
    publishable: spec.publishable !== false
  };
}

function syncPageTypeFromDocument(draft: KnowledgeRuleConfig, doc: DocumentTypeSpec): void {
  const pageTypeId = doc.defaultPageTypeId || doc.id;
  const existing = draft.pageTypes[pageTypeId];
  draft.pageTypes[pageTypeId] = normalizePageType({
    id: pageTypeId,
    label: existing?.label || doc.label.replace(/文档$/, ""),
    dir: existing?.dir || `${pageTypeId}s`,
    template: existing?.template || `${doc.id}.md`,
    requiredSections: [...doc.wikiSpecTemplate.requiredSections],
    requiredFacts: [...doc.wikiSpecTemplate.requiredFacts],
    evidenceRequired: doc.wikiSpecTemplate.evidenceRequired,
    publishable: doc.publishable !== false
  });
}

function normalizePageType(spec: PageTypeSpec): PageTypeSpec {
  return {
    id: normalizeId(spec.id),
    label: spec.label.trim() || spec.id,
    dir: spec.dir.trim() || `${spec.id}s`,
    template: spec.template.trim() || `${spec.id}.md`,
    requiredSections: [...(spec.requiredSections ?? [])],
    requiredFacts: [...(spec.requiredFacts ?? [])],
    evidenceRequired: spec.evidenceRequired !== false,
    publishable: spec.publishable !== false
  };
}

function normalizeEntityType(spec: EntityTypeSpec): EntityTypeSpec {
  const id = normalizeId(spec.id);
  return { id, label: spec.label.trim() || id, publishable: spec.publishable !== false };
}

function normalizeRelationType(spec: RelationTypeSpec): RelationTypeSpec {
  const id = normalizeId(spec.id);
  return {
    id,
    label: spec.label.trim() || id,
    direction: spec.direction === "bidirectional" ? "bidirectional" : "source_to_target",
    publishable: spec.publishable !== false,
    autoGenerated: Boolean(spec.autoGenerated)
  };
}

function cloneGovernanceRules(rules?: KnowledgeGovernanceRules): KnowledgeGovernanceRules {
  const base = defaultGovernanceRules();
  const source = rules ?? base;
  return {
    schema: { ...base.schema, ...(source.schema ?? {}) },
    evidence: {
      ...base.evidence,
      ...(source.evidence ?? {}),
      requiredComponentKinds: [...(source.evidence?.requiredComponentKinds ?? base.evidence.requiredComponentKinds)],
      citationRequiredOkfTypes: [...(source.evidence?.citationRequiredOkfTypes ?? base.evidence.citationRequiredOkfTypes)],
    },
    trust: { ...base.trust, ...(source.trust ?? {}) },
    lint: {
      ...base.lint,
      ...(source.lint ?? {}),
      enabledDomains: [...(source.lint?.enabledDomains ?? base.lint.enabledDomains)],
      blockingDomains: [...(source.lint?.blockingDomains ?? base.lint.blockingDomains)],
    },
    agent: { ...base.agent, ...(source.agent ?? {}) },
  };
}

export function defaultGovernanceRules(): KnowledgeGovernanceRules {
  return {
    schema: {
      requireFrontmatter: true,
      requireOkfType: true,
      requireDescription: true,
      requireTags: true,
      allowObsidianLinks: false,
      linkMode: "okf_absolute",
    },
    evidence: {
      requiredComponentKinds: ["wiki_page", "table_wiki_page"],
      citationRequiredOkfTypes: ["system_rule", "activity_template", "table_schema", "ui_flow", "numerical_convention"],
      autoBackfillOnPublish: true,
      missingEvidenceSeverity: "blocking",
    },
    trust: {
      policyVersion: "v2-lite",
      trustedMinScore: 0.85,
      usableMinScore: 0.7,
      reviewMinScore: 0.55,
      blockBelowScore: 0.55,
      warnBelowScore: 0.75,
      blockOnLowTrust: false,
    },
    lint: {
      enabledDomains: ["links", "evidence", "graph", "trust", "table_dependencies", "mcp_feedback"],
      blockingDomains: ["evidence", "trust", "table_dependencies", "mcp_feedback"],
      failPublishOnBlocking: false,
    },
    agent: {
      includeTrustInMcp: true,
      includeEvidenceInMcp: true,
      recordUnresolvedQueries: true,
      repeatedMissBlockingThreshold: 3,
    },
  };
}

function normalizeId(value: string): string {
  return value.trim().replace(/\s+/g, "_");
}

function nextId(prefix: string, existing: string[]): string {
  const taken = new Set(existing);
  let index = existing.length + 1;
  let candidate = `${prefix}_${index}`;
  while (taken.has(candidate)) {
    index += 1;
    candidate = `${prefix}_${index}`;
  }
  return candidate;
}
